#!/usr/bin/env python3
"""Build a standalone GODALGO terminal executable.

    pip install pyinstaller
    python build-exe.py              # fast-launching folder build (default)
    python build-exe.py --onefile    # single file, much slower to start

Produces ``dist/godalgo-terminal/`` -- a folder containing the executable and
its libraries, which runs the terminal with no Python installation on the
target machine.

**Why a folder and not a single file.** A onefile build is one executable, but
it pays for that on every launch: the bootloader unpacks the entire ~150MB
archive into a temporary directory before any code runs. Measured here that is
about 12 seconds cold and 3.5 warm, and it is materially worse on Windows,
where Defender scans each extracted file as it appears. A onedir build maps its
libraries directly from disk and skips the unpack entirely.

The application's own imports are not the bottleneck and never were: the UI
import path measures 248ms and pulls in neither ccxt, scipy nor statsmodels.
Optimising Python startup here would have been effort spent on the wrong thing.

The two things that break a naive PyInstaller build of this project:

* **Static files.** The UI is served from ``godalgo/ui/static``. PyInstaller
  bundles imported modules, not data, so without an explicit mapping the
  executable starts, serves the API, and returns 404 for the page itself --
  which looks like a server fault rather than a packaging one.
* **Hidden imports.** uvicorn and ccxt resolve much of their machinery by name
  at runtime. Static analysis cannot see those, so they must be named here or
  the binary fails on first request rather than at build time.
"""

from __future__ import annotations

import argparse
import shutil
import subprocess
import sys
from datetime import UTC, datetime
from pathlib import Path

ROOT = Path(__file__).parent
STATIC = ROOT / "src" / "godalgo" / "ui" / "static"
SEPARATOR = ";" if sys.platform == "win32" else ":"

# Resolved at runtime rather than imported, so PyInstaller cannot infer them.
HIDDEN = [
    "uvicorn.logging",
    "uvicorn.loops.auto",
    "uvicorn.loops.asyncio",
    "uvicorn.protocols.http.auto",
    "uvicorn.protocols.http.h11_impl",
    "uvicorn.protocols.websockets.auto",
    "uvicorn.protocols.websockets.websockets_impl",
    "uvicorn.lifespan.on",
    "ccxt.async_support",
    "ccxt.pro",
    "statsmodels.tsa.stattools",
    "scipy.special.cython_special",
    # Imported only inside a branch of run-terminal.py's main().
    "godalgo.service",
]

# Excluded to keep the bundle from carrying things it never uses. Every module
# left in is a file the loader may touch and, on Windows, one more file for
# Defender to inspect.
EXCLUDE = [
    "matplotlib", "tkinter", "PyQt5", "PySide2", "PySide6", "IPython",
    "notebook", "jupyter", "pytest", "_pytest", "sphinx", "docutils",
    "setuptools", "pip", "wheel",
]


def _write_build_stamp() -> None:
    """Record which commit this build came from.

    Without it, "the fix is not working" cannot be distinguished from "an older
    copy is still running" -- which cost a full debugging round when a second
    launch failed to bind its port and the previous build kept serving.
    """
    commit = "unknown"
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"],
            capture_output=True, text=True, timeout=10, cwd=ROOT, check=False,
        )
        if result.returncode == 0 and result.stdout.strip():
            commit = result.stdout.strip()
    except (OSError, subprocess.SubprocessError):
        pass

    stamp = ROOT / "src" / "godalgo" / "_build_stamp.py"
    stamp.write_text(
        '"""Generated by build-exe.py. Not committed."""\n\n'
        f'COMMIT = {commit!r}\n'
        f'BUILT_AT = {datetime.now(UTC).isoformat(timespec="seconds")!r}\n',
        encoding="utf-8",
    )
    print(f"build stamp: {commit}")


def main() -> int:
    parser = argparse.ArgumentParser(description="Build the GODALGO terminal")
    parser.add_argument(
        "--onefile", action="store_true",
        help="single executable instead of a folder; starts far slower "
             "because the whole archive unpacks on every launch",
    )
    args = parser.parse_args()

    if not STATIC.exists():
        print(f"error: static files not found at {STATIC}", file=sys.stderr)
        return 1
    if shutil.which("pyinstaller") is None:
        print("error: pyinstaller not installed — run: pip install pyinstaller",
              file=sys.stderr)
        return 1

    _write_build_stamp()

    command = [
        "pyinstaller",
        "--onefile" if args.onefile else "--onedir",
        "--name", "godalgo-terminal",
        "--clean",
        "--noconfirm",
        # Strip symbols and drop optimisable bytecode. Smaller bundle, fewer
        # bytes to page in, and on Windows fewer bytes for Defender to scan.
        "--strip" if sys.platform != "win32" else "--noupx",
        # The mapping without which the packaged UI 404s on its own page.
        "--add-data", f"{STATIC}{SEPARATOR}godalgo/ui/static",
        "--paths", str(ROOT / "src"),
    ]
    for name in HIDDEN:
        command += ["--hidden-import", name]
    for name in EXCLUDE:
        command += ["--exclude-module", name]
    command.append(str(ROOT / "run-terminal.py"))

    print("building:", " ".join(command), "\n")
    result = subprocess.run(command, cwd=ROOT, check=False)
    if result.returncode != 0:
        return result.returncode

    name = "godalgo-terminal.exe" if sys.platform == "win32" else "godalgo-terminal"
    binary = (ROOT / "dist" / name) if args.onefile else (
        ROOT / "dist" / "godalgo-terminal" / name
    )
    if not binary.exists():
        print("error: build reported success but no binary was produced",
              file=sys.stderr)
        return 1

    if args.onefile:
        total = binary.stat().st_size
    else:
        folder = ROOT / "dist" / "godalgo-terminal"
        total = sum(f.stat().st_size for f in folder.rglob("*") if f.is_file())

    print(f"\nbuilt {binary} ({total / 1e6:.0f} MB total)")
    if not args.onefile:
        print("  ship the whole dist/godalgo-terminal folder -- the executable")
        print("  needs the libraries beside it")
    print("run it with:")
    print(f"  {binary} --demo        # fabricated positions, nothing traded")
    print(f"  {binary}               # attached to a real session")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
